import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'

import { fetchTracksChart, fetchTerm } from '../../utils/apiclient'

const initialState = {
  value: [],
  status: 'idle',  // idle, loading, suceeded, failed
  error: null,
  searchTerm: '',
  isSearch: false,
}

export async function fetchTracksChartThunk({index, limit} = {index: undefined, limit: undefined}) {

  const tracksChart = await fetchTracksChart({index: index, limit: limit})

  return tracksChart.data.tracks.data
}

export const trackChartEnded = createAsyncThunk(
  'trackList/trackChartEnded',
  fetchTracksChartThunk,
  {
    condition: (arg, { getState }) => {
      const { trackList } = getState()
      const fetchStatus = trackList.status
      if (fetchStatus === 'loading'){
        return false
      }
    }
  }
)

export async function fetchTermThunk({index, limit} = {index: undefined, limit: undefined}, thunkAPI) {
  const term = thunkAPI.getState().trackList.searchTerm
  const searchResult = await fetchTerm(term, {index, limit})

  // thunkAPI.dispatch(resetedTrackList())
  return searchResult.data.data
}

)

export const trackListSlice = createSlice({
  name: 'trackList',
  initialState,
  reducers: {
    searchedTerm: (state, action) => {
      state.searchTerm = action.payload
      state.isSearch = true
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [trackChartEnded.pending]: (state) => {state.status = 'loading'},
    [trackChartEnded.fulfilled]: (state, action) => {

      const chartTracks = action.payload
      const newTracks = chartTracks.map( track => {
        return {
          cover: track.album.cover,
          id: track.id,
          link: track.link,
          preview: track.preview,
          singer: track.artist.name,
          time: track.duration,
          title: track.title
        }
      })

      state.status = 'suceeded'
      state.value = state.value.concat(newTracks)
    }
  },
})

export const {searchedTerm} = trackListSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectTrackList = (state) => state.trackList.value

export default trackListSlice.reducer
